args = commandArgs(trailingOnly = TRUE)
pathToLonLats = "C:/Users/Marcus/Documents/FPMS/data/ExampleLonLats.csv"
pathToEdges = "C:/Users/Marcus/Documents/FPMS/data/EulerianEdges.csv"
plotType = "mst"
resultPath = "C:/Users/Marcus/Documents/FPMS/images/autoGenerated/ExampleEulerianPath.pdf"
pathToLonLats = args[1]
pathToEdges = args[2]
plotType = args[3]
resultPath = args[4]
require(ggplot2)


if (plotType == "mst") {
  plotLonLats = read.csv(pathToLonLats)
  edges = read.csv(pathToEdges)
  plotLonLats$lon = plotLonLats$lon - min(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat - min(plotLonLats$lat)
  plotLonLats$lon = plotLonLats$lon / max(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat / max(plotLonLats$lat)
  # add one dummy arc since the the number of edges of an MST is always one less than the amount of nodes
  plotData = cbind(plotLonLats, fromLat = c(plotLonLats$lat[edges$from], plotLonLats$lat[edges$from[1]]),
                   fromLon = c(plotLonLats$lon[edges$from], plotLonLats$lon[edges$from[1]]),
                   toLat = c(plotLonLats$lat[edges$to], plotLonLats$lat[edges$to[1]]), 
                   toLon = c(plotLonLats$lon[edges$to], plotLonLats$lon[edges$to[1]]))
  print(nrow(plotData))
  
  pdf(resultPath)
  ggplot(data = plotData, aes(x = lat, y = lon)) + geom_point(size = 8) + theme_bw() + 
    geom_text(aes(label = rownames(plotData), hjust = 0, vjust = -1), size = 12) + 
    scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
                                                   axis.text.y=element_blank(),axis.ticks=element_blank(),
                                                   axis.title.x=element_blank(),
                                                   axis.title.y=element_blank(), legend.position = "none") +
    geom_curve(aes(x = fromLat, y = fromLon, xend = toLat, yend = toLon), 
               curvature = 0, ncp = 50, size = 1)
}
if (plotType == "mwm") {
  plotLonLats = read.csv(pathToLonLats)
  lonLatsLength = nrow(plotLonLats)-1
  edges = read.csv(pathToEdges)
  plotLonLats$lon = plotLonLats$lon - min(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat - min(plotLonLats$lat)
  plotLonLats$lon = plotLonLats$lon / max(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat / max(plotLonLats$lat)
  plotLonLats$names = rownames(plotLonLats)
  # increase size artificially for data frame merging
  for (i in (nrow(plotLonLats)+1):nrow(edges)) {
    plotLonLats = rbind(plotLonLats, plotLonLats[1,])
    plotLonLats$names[i] = ""
  }
  
  # assign groups for linetype
  for (i in 1:lonLatsLength) {
    plotLonLats$group[i] = 1
  }
  for (i in (lonLatsLength+1):nrow(edges)) {
    plotLonLats$group[i] = 2
  }
  plotLonLats$group = as.factor(plotLonLats$group)
  plotData = cbind(plotLonLats, fromLat = plotLonLats$lat[edges$from],
                   fromLon = plotLonLats$lon[edges$from],
                   toLat = plotLonLats$lat[edges$to], 
                   toLon = plotLonLats$lon[edges$to])
  
  pdf(resultPath)
  ggplot(data = plotData, aes(x = lon, y = lat)) + geom_point(size = 8) + theme_bw() + 
    geom_text(aes(label = plotData$names, hjust = 0, vjust = -1), size = 12) + 
    scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
                                                   axis.text.y=element_blank(),axis.ticks=element_blank(),
                                                   axis.title.x=element_blank(),
                                                   axis.title.y=element_blank(), legend.position = "none") +
    geom_curve(aes(x = fromLat, y = fromLon, xend = toLat, yend = toLon, lty = group), 
               curvature = 0, ncp = 50, size = 1)
}

if (plotType == "euler") {
  plotLonLats = read.csv(pathToLonLats)
  edges = read.csv(pathToEdges)
  # compute path
  path =  c(edges$from[1],edges$to[1])
  start = edges$to[1]
  for (i in 2:nrow(edges)) {
    if (edges$from[i] == start) {
      start = edges$to[i]
    }
    else start = edges$from[i]
    path = c(path, start)
  }
  # name order and redundant nodes
  redundantIndices = numeric()
  singleOrder = numeric()
  for (i in 1:length(path)) {
    if (path[i] %in% singleOrder) redundantIndices = c(redundantIndices, i)
    else singleOrder = c(singleOrder, path[i])
  }
  # find correspondence to redundant number
  correspondence = path[redundantIndices]
  
  names = character(0)
  for (i in 1:length(singleOrder)) {
    if (i %in% correspondence) {
      names[i] = which(path == i)[1]
      temp = which(correspondence == i)
      for (j in 1:length(temp)) {
        names[i] = paste(names[i], "/", redundantIndices[temp[j]], sep = "")
      }
    }
    else names[i] = as.character(which(path == i))
  }
  
  plotLonLats$lon = plotLonLats$lon - min(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat - min(plotLonLats$lat)
  plotLonLats$lon = plotLonLats$lon / max(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat / max(plotLonLats$lat)
  plotLonLats$names = names
  
  # insert dummies
  for (i in (nrow(plotLonLats)+1):nrow(edges)) {
    plotLonLats = rbind(plotLonLats, c(plotLonLats$lon[1], plotLonLats$lat[1], ""))
  }
  
  plotData = cbind(plotLonLats, fromLat = plotLonLats$lat[path[1:(length(path)-1)]],
                   fromLon = plotLonLats$lon[path[1:(length(path)-1)]],
                   toLat = plotLonLats$lat[path[2:length(path)]], 
                   toLon = plotLonLats$lon[path[2:length(path)]])
  
  pdf(resultPath)
  ggplot(data = plotData, aes(x = as.numeric(lon), y = as.numeric(lat))) + geom_point(size = 8) + theme_bw() + 
    geom_text(aes(label = as.factor(plotData$names), hjust = 0, vjust = -1), size = 12, fontface = "italic") + 
    scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
                                                   axis.text.y=element_blank(),axis.ticks=element_blank(),
                                                   axis.title.x=element_blank(),
                                                   axis.title.y=element_blank(), legend.position = "none") +
    geom_curve(aes(x = as.numeric(as.character(fromLon)), y = as.numeric(as.character(fromLat)), xend = as.numeric(as.character(toLon)), 
                   yend = as.numeric(as.character(toLat))), 
               arrow = arrow(length = unit(0.5, "cm"), type = "closed"), curvature = 0.15, ncp = 50, size = 1)
}
if (plotType == "tsp") {
  plotLonLats = read.csv(pathToLonLats)
  nodes = read.csv(pathToEdges, header = FALSE)
  
  plotLonLats$lon = plotLonLats$lon - min(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat - min(plotLonLats$lat)
  plotLonLats$lon = plotLonLats$lon / max(plotLonLats$lon)
  plotLonLats$lat = plotLonLats$lat / max(plotLonLats$lat)
  
  
  plotData = cbind(plotLonLats, fromLat = plotLonLats$lat[unlist(nodes$V1[1:(nrow(nodes)-1)])],
                   fromLon = plotLonLats$lon[unlist(nodes$V1[1:(nrow(nodes)-1)])],
                   toLat = plotLonLats$lat[unlist(nodes$V1[2:nrow(nodes)])], 
                   toLon = plotLonLats$lon[unlist(nodes$V1[2:nrow(nodes)])])
  
  pdf(paste(resultPath, nrow(nodes)-1, ".pdf", sep = ""))
  ggplot(data = plotData, aes(x = as.numeric(lon), y = as.numeric(lat))) + geom_point(size = 8) + theme_bw() + 
    geom_text(aes(label = rownames(plotData), hjust = 0, vjust = -1), size = 12) + 
    scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(), legend.position = "none") +
    geom_curve(aes(x = fromLon, y = fromLat, xend = toLon, yend = toLat), 
               arrow = arrow(length = unit(0.5, "cm"), type = "closed"), curvature = 0.15, ncp = 50, size = 1)
}

if (plotType == "fpApproach") {
  require(ggmap)
  require(RgoogleMaps)
  plotLonLats = read.csv(pathToLonLats)
  nodes = read.csv(pathToEdges, header = FALSE)
  
  #plotLonLats$lon = plotLonLats$lon - min(plotLonLats$lon)
  #plotLonLats$lat = plotLonLats$lat - min(plotLonLats$lat)
  #plotLonLats$lon = plotLonLats$lon / max(plotLonLats$lon)
  #plotLonLats$lat = plotLonLats$lat / max(plotLonLats$lat)
  
  center = c(((max(plotLonLats$lon) + min(plotLonLats$lon))/2), ((max(plotLonLats$lat) + min(plotLonLats$lat))/2))
  zoom <- min(MaxZoom(range(plotLonLats$lon), range(plotLonLats$lat)))
  
  #mapImageData = get_googlemap(c(lon=7.628496, lat=51.964711), zoom=13)
  mapImageData = get_googlemap(center, zoom=zoom)
  
  for (i in unique(nodes[,2])) {
    nodesToPlot = unique(nodes[which(nodes[,2] == i),1])
    currentPlotData = plotLonLats[nodesToPlot,]
    from = nodesToPlot
    to = nodesToPlot[2:length(nodesToPlot)]
    to = c(to, 1)
    currentPlotData = cbind(currentPlotData, fromLat = plotLonLats$lat[from],
                            fromLon = plotLonLats$lon[from],
                            toLat = plotLonLats$lat[to], 
                            toLon = plotLonLats$lon[to])
    pdf(paste(resultPath, i, ".pdf", sep = ""))
    print(ggmap(mapImageData, extend = "device") + geom_point(aes(x = lon, y = lat), data = currentPlotData, size = 4) + theme_bw() + 
      theme(axis.line=element_blank(),axis.text.x=element_blank(),
            axis.title.x=element_blank(), axis.text.y = element_blank(),
            axis.title.y=element_blank(), legend.position = "none") +
      geom_curve(aes(x = fromLon, y = fromLat, xend = toLon, yend = toLat), data = currentPlotData,
                 arrow = arrow(length = unit(0.5, "cm"), type = "closed"), curvature = 0.15, ncp = 50, size = 1) +
        coord_cartesian())
  }
}








# archive
if (FALSE) {
  from = numeric(0)
  to = numeric(0)
  currentGroup = nodes[1,2]
  group = numeric(0)
  for (i in 1:(nrow(nodes)-1)) {
    if (currentGroup == nodes[i+1,2]) {
      from = c(from, nodes[i,1])
      to = c(to, nodes[i+1,1])
      group = c(group, currentGroup)
    }
    else currentGroup = nodes[i+1,2]
  }
  
  # insert dummy nodes
  for (i in (nrow(plotLonLats)+1):length(to)) {
    plotLonLats = rbind(plotLonLats, plotLonLats[1,])
  }
  
  plotData = cbind(plotLonLats, fromLat = plotLonLats$lat[from],
                   fromLon = plotLonLats$lon[from],
                   toLat = plotLonLats$lat[to], 
                   toLon = plotLonLats$lon[to])
  plotData = cbind(plotData, group = as.factor(group))
  
  ggplot(data = plotData[c(1,2,5,7,8,9,10,23,25),], aes(x = lon, y = lat)) + geom_point(size = 8)
  
  pdf(resultPath)
  ggplot(data = plotData, aes(x = lon, y = lat, lty = group)) + geom_point(size = 8) + theme_bw() + 
    scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
    geom_text(aes(label = rownames(plotData), hjust = 0, vjust = -1), size = 12) + 
    theme(axis.line=element_blank(),axis.text.x=element_blank(),
          axis.text.y=element_blank(),axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(), legend.position = "none") +
    geom_curve(aes(x = fromLon, y = fromLat, xend = toLon, yend = toLat), curvature = 0, ncp = 50, size = 1)
  
  
  
  
  print(ggplot(data = currentPlotData, aes(x = lon, y = lat)) + geom_point(size = 8) + theme_bw() + 
          scale_y_continuous(limits = c(0, 1.1)) + scale_x_continuous(limits = c(0, 1.1)) + 
          theme(axis.line=element_blank(),axis.text.x=element_blank(),
                axis.text.y=element_blank(),axis.ticks=element_blank(),
                axis.title.x=element_blank(),
                axis.title.y=element_blank(), legend.position = "none") +
          geom_curve(aes(x = fromLon, y = fromLat, xend = toLon, yend = toLat), 
                     arrow = arrow(length = unit(0.5, "cm"), type = "closed"), curvature = 0.15, ncp = 50, size = 1))
}
